### ISSUE TITLE
Hello, I have tried your tools without success in general. #27

### ISSUE THREAD

**Issue by LordGarfio** [katahiromz/vista2xp#28]
Hello, I have tried your tools without success in general.
· vista2xp v0.8.4 by katahiromz.
· vista2xp v0.8.3 by katahiromz.
· vista2xp v0.8.2 by katahiromz.

RegDeleteKeyExW ERROR:
ImgDrive v2.1.8 FREEWARE PORTABLE by www.yubsoft.com/imgdrive do not works still.
RegDeleteKeyExW ERROR:
![ImgDrive v2 1 8 XP](https://github.com/katahiromz/vista2xp/assets/65074751/42f84af3-aced-4430-a67c-6c5b3c1593f8)

Direct Folders v4.2 Freeware Installer and TeraCopy Pro v3.17 Freeware Installer by Code Sector which is using Advanced Installer v21.1.x from www.caphyon.com.
CreateEventExW ERROR:
![Direct Folders v4 2 Free Installer](https://github.com/katahiromz/vista2xp/assets/65074751/702b5901-ac44-4f13-bf62-7dce04d588fd)
![TeraCopy Pro v3 17 Free Installer](https://github.com/katahiromz/vista2xp/assets/65074751/198924a0-8640-4d97-a9d0-798a55f65c5b)

FastCopy v5.7.12 ERROR:
![FastCopy x32 v5 7 12 XP](https://github.com/katahiromz/vista2xp/assets/65074751/62f4aea9-66b7-492b-b7de-605570a25e60)

FastCopy v5.7.12 FREEWARE by fastcopy.jp With Vista-to-XP application converter, WORKS very good.
![FastCopy x32 v5 7 12 XP works](https://github.com/katahiromz/vista2xp/assets/65074751/08426fbf-eeda-4402-8d3a-2df4f67329ac)

Thank you in advanced.

_Originally posted by @LordGarfio in https://github.com/katahiromz/vista2xp/issues/27#issuecomment-2150654052_

**Comment by katahiromz** [comment]
Done.
片山博文MZ

2024年6月6日(木) 5:37 LordGarfio ***@***.***>:

**Comment by LordGarfio** [comment]
**ImgDrive v2.1.8 Portable**, still does not work. I see that the problem is in the conversion of the **ADVAPI32.DLL.RegDeleteKeyExW** function.

![imgdrive exe](https://github.com/katahiromz/vista2xp/assets/65074751/3331274d-80ec-4513-8078-309db4481461)

Below, I leave you a list of files in which your **v2xadv32.dll** library is not available after the conversion, and that using **vista2xp v0.8.5 by katahiromz**: 

language\
vista2xp-0.8.5-bin\
Vista2XP-Backup\
x86\
imgdrive.cat
imgdrive.dll
imgdrive.exe
imgdrive.inf
**v2xker32.dll
v2xol.dll**

![vista2xp v0 8 5 by katahiromz](https://github.com/katahiromz/vista2xp/assets/65074751/5c71d624-a8b2-47bc-9e8f-6b8065ec3336)

Why **v2xol.dll** library ?.

ImgDrive FREEWARE Downloads:
https://download.yubsoft.com/imgdrive_2.1.8.exe
https://download.yubsoft.com/imgdrive_2.1.8_portable.zip


On the other hand, TeraCopy Pro v3.17 Installer (teracopy.exe) and Direct Folders v4.2 Installer (directfolders.exe), now require another API: **GetFinalPathNameByHandleW**. from **v2xker32.dll**

![teracopy exe](https://github.com/katahiromz/vista2xp/assets/65074751/a8a9dee0-31ea-4b83-908b-6888d594ec37)
![directfolders exe](https://github.com/katahiromz/vista2xp/assets/65074751/d7da8f38-b2bb-41e0-afdb-5871476c597b)


Cheers.

**Comment by katahiromz** [comment]
Done.

**Comment by LordGarfio** [comment]
vista2xp v0.8.6 has a problem during the convertion of ImgDrive, do not works, it crashes like this:

![vista2xp-0 8 6-bin error1](https://github.com/katahiromz/vista2xp/assets/65074751/9faa801e-0f40-44d3-90d5-645a3866d2a9)
![vista2xp-0 8 6-bin error2](https://github.com/katahiromz/vista2xp/assets/65074751/493ade11-44ed-488e-ba7d-9f2d11a76f71)
![vista2xp-0 8 6-bin error3](https://github.com/katahiromz/vista2xp/assets/65074751/93e66396-3601-4802-b716-44166c79783d)


I see that the Kernel32.InitializeCriticalSectionEx function will be supported in vista2xp v0.8.7.

![directfolders_InitializeCriticalSectionEx](https://github.com/katahiromz/vista2xp/assets/65074751/f81ac4d1-298d-465f-96c4-ea01958226d5)
![teracopy_InitializeCriticalSectionEx](https://github.com/katahiromz/vista2xp/assets/65074751/cad2aca1-c51b-42eb-a8d6-6d49e3885cc7)

;-)

**Comment by katahiromz** [comment]
Fixed.

**Comment by LordGarfio** [comment]
**¡Nice Hook! Now ImgDrive v2.1.8 is loading** with surprise:

![imgdrive exe 2 1 8 works](https://github.com/katahiromz/vista2xp/assets/65074751/49a282cc-9326-4f6a-b6c6-0c10e2649a87)

Now **Kernel32.Wow64DisableWow64FsRedirection** is now required.

![directfolders exe WoW64](https://github.com/katahiromz/vista2xp/assets/65074751/2182a581-f181-4602-a5a9-d4da22fd14eb)
![teracopy exe WoW64](https://github.com/katahiromz/vista2xp/assets/65074751/2def7782-82e6-4f35-b908-30b4cbf222b7)

**Wow64DisableWow64FsRedirection API** reminded me the case of ExeInfoPE by ASL, here: https://github.com/ExeinfoASL/ASL/issues/9

Thank you.

**Comment by LordGarfio** [comment]
**Addional Information by the way**

DriveImg do the next checks:

1. Return: 0x00050001 on Windows XP at 00422081 | call dword ptr ds:[<**kernel32.GetNativeSystemInfo**>].
2. Return: Zero on Windows XP and 6.1 was checked.at 004220C4 | call dword ptr ds:[<**v2xker32.GetVersionExW**>].
3. Returned Zero:**GetProcessAddress wintrust.CryptCATAdminAcquireContext2** (**SHA-2** update support patches is missing).

https://yubsoft.com/imgdrive/windows-7-updates-for-sha-2-support.html

> ImgDrive cannot be installed on Microsoft Windows 7 and Microsoft Windows Server 2008 R2 if the following updates are not installed:
> 
>     KB4490628 (update from 12 march 2019);
>     KB4474419 (update from 23 september 2019).
> 
> Installation error occurs as a result of Microsoft having updated the algorithm for signing modules and drivers of third-party applications. Now modules and drivers of third-party applications are signed using SHA256 hashing algorithm. You need to install updates for KB4490628 and KB4474419, so that ImgDrive modules and drivers could be signed using SHA256 hashing algorithm.



**And SHA is supported in an updated BCRYPT.DLL:**
https://github.com/Blaukovitch/bcrypt-XP

Windows XP bcrypt.dll - Cryptography API Next Generation (CNG)

Supporting small set of CNG API (https://learn.microsoft.com/en-us/windows/win32/seccng/cng-portal)

support crypto context - only HASH:

BCRYPT_SHA1_ALGORITHM
BCRYPT_MD5_ALGORITHM
BCRYPT_RNG_ALGORITHM
BCRYPT_SHA256_ALGORITHM
BCRYPT_SHA384_ALGORITHM
BCRYPT_SHA512_ALGORITHM
BCRYPT_ECDSA_P256_ALGORITHM
BCRYPT_ECDSA_P384_ALGORITHM

with HMAC

hash API available:

BCryptCloseAlgorithmProvider
BCryptCreateHash
BCryptDestroyHash
BCryptFinishHash
BCryptGenRandom
BCryptHashData
BCryptOpenAlgorithmProvider


Cheers.

**Comment by katahiromz** [comment]
![image](https://github.com/katahiromz/vista2xp/assets/2107452/4e93a52f-afdd-42cd-b037-f4a161d335b0)
I see.

**Comment by LordGarfio** [comment]
I see that ImgDrive uses the imgdrive.sys driver.

I am not clear if Vista2XP is enough to perform the Trampoline.

I have seen another project called NTOSKRNL_Emu - Library of missed NTOSKRNL import functions: https://github.com/GeorgeK1ng/NTOSKRNL_Emu.

I hope you find it useful to improve Vista2XP.

**Comment by katahiromz** [comment]
`Wow64DisableWow64FsRedirection` is added.

**Comment by LordGarfio** [comment]
**Code Sector Direct Folders v4.2 (directfolders.exe).**
**Code Sector TeraCopy Pro v3.17 (teracopy.exe).**

I have seen that it is need implement some APIs more for above installers (**Advanced Installer v21.1.x from [www.caphyon.com](http://www.caphyon.com/)**.).

1) LCMapStringEx is missing.
2) CompareStringEx is there.
3) GetLocaleInfoEx and ReOpenFile **by the way** is missing too.

**LCMapStringEx:**
![directfolders exe_LCMapStringEx_1](https://github.com/katahiromz/vista2xp/assets/65074751/abb020d4-8eb0-450a-a86e-1f9c3c1cc5f3)
![directfolders exe_LCMapStringEx_2](https://github.com/katahiromz/vista2xp/assets/65074751/cb7e8e42-a737-49f5-9444-81d41aca6276)


**LCMapStringEx **HACK** did not work (it  explodes):**
![directfolders exe_LCMapStringEx_1_HACK](https://github.com/katahiromz/vista2xp/assets/65074751/93f289c6-2a4a-4541-b153-4ac00efad7f1)
![directfolders exe_LCMapStringEx_2_HACK](https://github.com/katahiromz/vista2xp/assets/65074751/ba5a97e8-3288-4183-8344-be0ee1344d7e)


**CompareStringEx is good:**
![directfolders exe_CompareStringEx_1](https://github.com/katahiromz/vista2xp/assets/65074751/8ff51c95-3f47-42f3-b7d8-dbe467bb6c29)
![directfolders exe_CompareStringEx_2](https://github.com/katahiromz/vista2xp/assets/65074751/0252f76f-0094-468a-bbab-5bb591d78696)


**Dependency Walker v2.2.6000**
![directfolders exe_Kernel32_DW](https://github.com/katahiromz/vista2xp/assets/65074751/930e48d5-bfc5-4fbf-8495-5c18e2af0f2a)
![directfolders exe_User32_DW](https://github.com/katahiromz/vista2xp/assets/65074751/377f1d88-e242-4c42-8e3c-1bc884634c4c)
![directfolders exe_UXTheme_DW](https://github.com/katahiromz/vista2xp/assets/65074751/2a30fff0-1b70-46b7-b069-88b5cc9eef39)


Sincerely, I no longer know if the trampolines are possible for these cases.

Cheers.

**Comment by LordGarfio** [comment]
### **VISTA2XP v0.8.8 has processing errors**

--------------------------------------------------
WinRAR v7.01 - Bad patching using vista2xp v0.8.8
--------------------------------------------------

I comment you that Vista2XP on WinRAR v7.01, patches the wrong libraries on WinRAR.exe and RarExt.dll with ole32.dll instead of advapi32.dll which would be the correct one. A hand-corrected image is shown below.

**[7 missing functions in KERNEL32]**
![WRAR-x32-701-kernel32](https://github.com/katahiromz/vista2xp/assets/65074751/12f04438-ab2c-4757-9aac-d5bb05501ba8)

**[Now, only 3 functions are missing in KERNEL32 by using vista2xp]**
![WRAR-x32-701-v2xker32 dll](https://github.com/katahiromz/vista2xp/assets/65074751/72426cf0-767a-41da-b3f0-be649e916351)

**_[OLE32.DLL (v2xol.dll) was patched instead of ADVAPI32.DLL], it is an error_**
![WRAR-x32-701-v2xol dll](https://github.com/katahiromz/vista2xp/assets/65074751/e6d25a83-5d1d-4094-bfb1-a3c95db6e3f0)

**_[ADVAPI32 FIXED (v2xadv32.dll instead of v2xol.dll) by hand]_**
![WRAR-x32-701-v2xadv32 dll](https://github.com/katahiromz/vista2xp/assets/65074751/b5faf1d1-9be6-49a3-88b5-14de75ec1003)

**[COMCTL32.DLL Only Ordinal 381d / 17Dh is present, No Hint, No Function Name]**
![WRAR-x32-701-ComCTL32 DLL](https://github.com/katahiromz/vista2xp/assets/65074751/db1b595c-dc06-4da4-91bd-e45e54c65227)



**[LATEST COMCTL32.DLL RELEASE BY MICROSOFT]:
SECURITY UPDATE FOR WINDOWS XP SP3, EMBEDDED AND POSREADY 2009 (KB2296011)**

**COMCTL32.DLL v5.82.2900.6028** Direct Downloads for Security Update for **Windows XP Embedded (KB2296011)**
https://catalog.s.download.windowsupdate.com/msdownload/update/software/secu/2010/09/windowsxp-kb2296011-x86-custom-enu_29b33ff228ac6b2e6f088a295bf549a35d0f0746.exe

**COMCTL32.DLL v5.82.2900.6028** Direct Downloads for Security Update for **Windows XP SP3 (KB2296011)**
https://catalog.s.download.windowsupdate.com/msdownload/update/software/secu/2010/09/windowsxp-kb2296011-x86-enu_95ff937b7a8443ddb8ae0579da94690ac3a85d0d.exe


**Direct Downloads for WinRAR v7.01 Installers:** 
https://www.rarlab.com/rar/winrar-x32-701.exe
https://www.rarlab.com/rar/winrar-x32-701jp.exe
https://www.rarlab.com/rar/winrar-x32-701es.exe


Next, I write the missing functions from WINRAR.EXE, RAREXT.DLL, WINCON32.SFX, DEFAULT32.SFX, ZIP32.SFX (All missing functions are the same): 

**WINRAR.EXE**
WinRAR.exe -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_InDllMainContext
WinRAR.exe -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_SetRedirectRegistryForThread
WinRAR.exe -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_Initialize
WinRAR.exe -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_Uninitialize
WinRAR.exe -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_GetOriginatingThreadId
WinRAR.exe -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportCloseHandle
WinRAR.exe -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportSetParameter
WinRAR.exe -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportSubmit
WinRAR.exe -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportCreate
WinRAR.exe -> SHELL32.DLL -> EFSADU.DLL -> EfsDetail
WinRAR.exe -> SHLWAPI.DLL -> MPR.DLL -> WNetRestoreConnectionA



**RAREXT.DLL**
RarExt.dll -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_InDllMainContext
RarExt.dll -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_SetRedirectRegistryForThread
RarExt.dll -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_Initialize
RarExt.dll -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_Uninitialize
RarExt.dll -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_GetOriginatingThreadId
RarExt.dll -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportCloseHandle
RarExt.dll -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportSetParameter
RarExt.dll -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportSubmit
RarExt.dll -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportCreate
RarExt.dll -> SHELL32.DLL -> EFSADU.DLL -> EfsDetail
RarExt.dll -> SHLWAPI.DLL -> MPR.DLL -> WNetRestoreConnectionA



**WINCON32.SFX**
WinCon32.sfx -> ADVAPI32.DLL -> SECUR32.DLL -> NETAPI32.DLL -> DNSAPI.DLL -> IPHLPAPI.DLL -> MPRAPI.DLL -> SETUPAPI.DLL -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_InDllMainContext
WinCon32.sfx -> ADVAPI32.DLL -> SECUR32.DLL -> NETAPI32.DLL -> DNSAPI.DLL -> IPHLPAPI.DLL -> MPRAPI.DLL -> SETUPAPI.DLL -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_SetRedirectRegistryForThread
WinCon32.sfx -> ADVAPI32.DLL -> SECUR32.DLL -> NETAPI32.DLL -> DNSAPI.DLL -> IPHLPAPI.DLL -> MPRAPI.DLL -> SETUPAPI.DLL -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_Initialize
WinCon32.sfx -> ADVAPI32.DLL -> SECUR32.DLL -> NETAPI32.DLL -> DNSAPI.DLL -> IPHLPAPI.DLL -> MPRAPI.DLL -> SETUPAPI.DLL -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_Uninitialize
WinCon32.sfx -> ADVAPI32.DLL -> SECUR32.DLL -> NETAPI32.DLL -> DNSAPI.DLL -> IPHLPAPI.DLL -> MPRAPI.DLL -> SETUPAPI.DLL -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_GetOriginatingThreadId
WinCon32.sfx -> ADVAPI32.DLL -> SECUR32.DLL -> NETAPI32.DLL -> DNSAPI.DLL -> IPHLPAPI.DLL -> MPRAPI.DLL -> SETUPAPI.DLL -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportCloseHandle
WinCon32.sfx -> ADVAPI32.DLL -> SECUR32.DLL -> NETAPI32.DLL -> DNSAPI.DLL -> IPHLPAPI.DLL -> MPRAPI.DLL -> SETUPAPI.DLL -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportSetParameter
WinCon32.sfx -> ADVAPI32.DLL -> SECUR32.DLL -> NETAPI32.DLL -> DNSAPI.DLL -> IPHLPAPI.DLL -> MPRAPI.DLL -> SETUPAPI.DLL -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportSubmit
WinCon32.sfx -> ADVAPI32.DLL -> SECUR32.DLL -> NETAPI32.DLL -> DNSAPI.DLL -> IPHLPAPI.DLL -> MPRAPI.DLL -> SETUPAPI.DLL -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportCreate
WinCon32.sfx -> ADVAPI32.DLL -> SECUR32.DLL -> NETAPI32.DLL -> DNSAPI.DLL -> IPHLPAPI.DLL -> MPRAPI.DLL -> SETUPAPI.DLL -> SHELL32.DLL -> EFSADU.DLL -> EfsDetail
WinCon32.sfx -> ADVAPI32.DLL -> SECUR32.DLL -> NETAPI32.DLL -> DNSAPI.DLL -> IPHLPAPI.DLL -> MPRAPI.DLL -> SETUPAPI.DLL -> SHLWAPI.DLL -> MPR.DLL -> WNetRestoreConnectionA



**DEFAULT32.SFX**
Default32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_InDllMainContext
Default32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_SetRedirectRegistryForThread
Default32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_Initialize
Default32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_Uninitialize
Default32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_GetOriginatingThreadId
Default32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportCloseHandle
Default32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportSetParameter
Default32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportSubmit
Default32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportCreate
Default32.sfx -> SHELL32.DLL -> EFSADU.DLL -> EfsDetail
Default32.sfx -> SHLWAPI.DLL -> MPR.DLL -> WNetRestoreConnectionA



**ZIP32.SFX**
Zip32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_InDllMainContext
Zip32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_SetRedirectRegistryForThread
Zip32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_Initialize
Zip32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_Uninitialize
Zip32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> IESHIMS.DLL -> IEShims_GetOriginatingThreadId
Zip32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportCloseHandle
Zip32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportSetParameter
Zip32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportSubmit
Zip32.sfx -> SHELL32.DLL -> SHDOCVW.DLL -> MSHTML.DLL -> IEFRAME.DLL -> WER.DLL -> WerReportCreate
Zip32.sfx -> SHELL32.DLL -> EFSADU.DLL -> EfsDetail
Zip32.sfx -> SHLWAPI.DLL -> MPR.DLL -> WNetRestoreConnectionA


-----------------------------------------------------------------------
UFS EXPLORER DATA RECOVERY v10.5 - Fake patching using vista2xp v0.8.8
-----------------------------------------------------------------------

I also comment you that sometimes Vista2XP does not patch some targets even if the successful message is issued (ufs-explorer-pro.exe), for example: 

**UFS v10.5.0.7027 Aplication** (ufs-explorer-pro.exe v10.5.0.7027)..
**UFS v10.5.0.7044 Installer** (MD5SUM: e072dc32987a78c5faa4210224ff32b6 *ufsxpci.exe) and **Program that is packed** (MD5: b746e3795bc09ca59c41a81abf988547 *ufs-explorer-pro.exe)..
**UFS v10.5.0.7027 Installer** (MD5SUM: dcfe651aec216e9f697079bbd0567c3f *ufsxpci10.5.exe) and **Program** (MD5: c7be7252522c8fdc9d854ae799d87865 *ufs-explorer-pro.exe).


**[15 missing functions in KERNEL32]**
![UFS v10 5 0 7027 Kernel32 dll](https://github.com/katahiromz/vista2xp/assets/65074751/dd76fe0c-653b-41f4-9bd9-e8e61ae241ed)

**[Now, only 4 functions are missing in KERNEL32]**
![UFS v10 5 0 7027 v2xker32 dll](https://github.com/katahiromz/vista2xp/assets/65074751/0bf3590e-1768-4fad-8e67-d281db69353a)

**[Missing function PowerReadFrienlyName in POWRPROF.DLL]**
![UFS v10 5 0 7027 POWRPROF DLL](https://github.com/katahiromz/vista2xp/assets/65074751/7a183863-a4f8-4e6d-90b7-d5f8b011f6a2)


**Direct Download for UFS Data Recovery v10.5 Build 7027 Installer:** 
https://www.upload.ee/files/16767700/ufsxpci10.5.exe.html

**Direct Download for UFS Data Recovery v10.5 Build 7044 Installer:** 
https://www.sysdevlabs.com/download/hist/ufsx/10.5/ufsxpci.exe

_Too much thank you Mr. katahiromz._

**Comment by LordGarfio** [comment]
###  ** Extended XP - Lets patch XP for newer apps **

**An old project to bring Windows Vista APIs to XP that is now abandoned.**

**_Extended XP Build Enviroment Source by Dibya_**
https://web.archive.org/web/20191108101116/http://ryanvm.net/forum/viewtopic.php?f=25&t=10631&

**BUILD.CMD**
nasm -f win32 ExKernel.asm 
golink /dll ExKernel.obj  advapi32.dll shell32.dll kernel32.dll ntdll.dll 
pause

**DOWNLOAD:** 
Last kernel binaries and Exkernel.dll build environment are here: 
https://web.archive.org/web/20191108101116/https://www.mediafire.com/file/4k48mb5tt73jmvy/BuildEnviroment.7z

**DIRECT DOWNLOAD:** 
https://web.archive.org/web/20240304153556if_/https://download1591.mediafire.com/8o3ifmjwkd9gPVEnj20GmoIwIvyc4uXcaG1OD6bhtzEhRZKTOwH88RU--HzulqcSHTWIdjeeAbnLHtD36Gg0CCdyB1T3q5qgxXQr5SQ4H0zxfYGhwmNKKQ5CvRfUyJFHfpwGM9AzKLw_wpPkBJErQPxC9uPxbCXZADNW2WR7fhIEfg/4k48mb5tt73jmvy/BuildEnviroment.7z

--------------------------------------------------

###  ** MORE UTIL TOOLS **

Mr. katahiromz, 

I leave here some more references to other tools to help you to facilitate the development of the great Vista2XP.

--------------------------------------------------

**All Dlls Dependencies v2.1.2 FREEWARE for Windows Xp, 7, 8, 10, 11 [April 28 2024]**
http://jacquelin.potier.free.fr/AllDllDeps/

All Dlls Dependencies is a static analyzer for Dlls dependencies.
It is a clone of Depends supporting Windows 7 and Windows 10 stub dlls.
Like Dependency Walker, it can analyze modules to find missing imported dlls or functions

Notice: For a dynamic analysis, use WinApiOverride (http://jacquelin.potier.free.fr/winapioverride32/) with LoadedLib.txt or Loadedfunc.txt monitoring files.


**Direct Download:** 
http://jacquelin.potier.free.fr/exe/AllDllDeps_bin.zip

--------------------------------------------------

**Vanara v4.0.2 [Jun 24, 2024]**
https://github.com/dahall/Vanara

A set of .NET libraries for Windows implementing PInvoke calls to many native Windows APIs with supporting wrapper.

This project contains various .NET assemblies that contain P/Invoke functions, interfaces, enums and structures from Windows libraries. Each assembly is associated with one or a few tightly related libraries. For example, Shlwapi.dll has all the exported functions from shlwapi.lib; Kernel32.dll has all for both kernel32.lib and kernelbase.lib.

All assemblies are available via NuGet and provide builds against .NET 4.5, 4.8, 5.0, 6.0, .NET Standard 2.0, Core 3.1 and support SourceLink (https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink). Extensions are available for WinForms, WPF, and UWP projects. If you need support for other .NET versions, look to versions 3.3.15 and earlier.


**PInvoke functions, interfaces, enums and structures - WinTrust, Gdi32, Shell32, Kernel32, ShlwAPI, User32, ...**
https://github.com/dahall/Vanara/tree/master/PInvoke

**Vanara.PInvoke.WinTrust NuGet Package**
https://www.nuget.org/packages/Vanara.PInvoke.WinTrust/4.0.2#supportedframeworks-body-tab

--------------------------------------------------

Regards.
